server/main.tf, server/variables.tf
Testing the terraform plan by adding rds definitions and creating a pull request. Opening this PR should trigger the github actions in ./github/workflows/pull_request.yml to run Terraform Plan. 
When this runs, we can see the output of the github action and tell if the plan indicates that the RDS database would actually get created.
=> chore: add rds db to terraform

db/sql/1_initial_schema.sql
closes #12 
This script was created by exporting the ER studio model to PostgreSQL DDL
=> chore: add initial db script

db/sql/1_initial_schema.sql
* swapped out SYSDATE to currrent_date to make work with postgres
=> postgres syntax

server/flyway/sql/V2__first_application.sql
=> #69 - Populate application database table

backend/api/app/crud.py, backend/api/app/schemas.py, backend/tests/conftest.py, backend/tests/test_crud.py
- Add SqlLite foreign key support through ("PRAGMA foreign_keys=ON")
- Fix existing failing tests.
- Minor reorganize code/tests.
=> Add sqllite foreignkey support for tests and fix existing failing tests.

.github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/task.md
* Got sick of having to go to a different repo to get these templates, adding them to the repo for easy access
=> Adding issue templates

.github/workflows/push.yml
* simplify the github actions that build the lambda package
=> fixing the push gha

infrastructure/frontend/cloudfront.tf
=> fix: 270 cloudfront s3 update etag

docker-compose.yml, server/flyway/sql/V12__add_roles.sql
=> feat: 155 migration script for fam roles

.github/workflows/reusable_auth_function_ci.yml, docker-compose.yml, infrastructure/server/flyway.tf, server/flyway/flyway-migrate.sh, server/flyway/sql/V13__add_roles_app_clients.sql
=> feat: 281 added logic for app client records in db

.github/workflows/reusable_terraform_frontend.yml
=> Append 'env' setting and enclose json with last '}'.

.github/workflows/reusable_terraform_frontend.yml, infrastructure/server/oidc_clients.tf, infrastructure/server/outputs.tf, infrastructure/server/variables_provided.tf, terraform/dev/terragrunt.hcl, terraform/prod/terragrunt.hcl, terraform/test/terragrunt.hcl
Easier to export this value from Terraform than to try to write it in with a bash script?
=> fix: add environment value to env json file

server/backend/api/alembic/env.py, server/backend/docker-compose.yml
Cleaning up issue 126 (feat/126-app-role-get), pulling things out into smaller pieces.  This work was completed to support the development on issue 126.
=> feat: 253 - add docker-compose that starts backend and runs migrations

frontend/src/components/GrantAccess.vue, frontend/src/components/Home.vue, frontend/src/components/ManageAccess.vue, frontend/src/components/PageTitle.vue, frontend/src/components/SelectApplication.vue, frontend/src/router/index.ts, frontend/src/services/http/HttpRequestInterceptors.ts, frontend/src/views/HomeView.vue
Part of the change for issue #178:
* Use vue-router "meta" to specify "title" for the route.
* Add a "PageTitle" common vue component for different pages to use.
=> Feat/178 frontend grant access  page title

frontend/src/components/GrantAccess.vue, frontend/src/components/ManageAccess.vue, frontend/src/components/SelectApplication.vue, frontend/src/main.ts, frontend/src/router/index.ts, frontend/src/services/ErrorService.ts, frontend/src/services/http/HttpCommon.ts, frontend/src/services/http/HttpResponseInterceptors.ts
- Refactoring toast messages and error handling;
- Interceptor for 401 error and redirecting to home;
- Adjusting 403 error;
=> Feat 309 access restriction frontend

frontend/src/services/http/HttpResponseInterceptors.ts
At retry.then() block => reset retryCount to 0.
=> fix/399 - Reset retryCount when retried request does come through successfully.

frontend/src/components/footer/Footer.vue, frontend/src/components/header/Header.vue, frontend/src/router/index.ts, frontend/src/views/AboutView.vue
- Removing contact us from header
- Adjusting footer with contact e-mail
=> Fix/428 - Hide Contact Us & About Us Page

infrastructure/server/oidc_clients_fom.tf, infrastructure/server/oidc_idp_idir.tf
- Remove "custom:idp_display_name" from general min list.
- Add "custom:idp_display_name" to oidc_clients_fom.tf
=> Add write permission for mapping on "custom:idp_display_name"

infrastructure/server/oidc_idp_bceid_business.tf
Have not tested this yet, but maybe it can piggyback off another deploy?
=> fix: configuration error in bceid prod

frontend/public/env.json, frontend/src/services/AuthService.ts, frontend/src/services/EnvironmentSettings.ts
=> Feat/464: Bypass Cognito Login UI

.github/workflows/dev_deployment.yml
=> Run dev deploy on push to main

infrastructure/server/oidc_clients_fom.tf
- added fom demo callback and logout url to fom-test client refs: #544
=> fix: #544 Add FOM demo callback and logout url to FOM-TEST client in terraform

infrastructure/server/aurora-v2.tf, scripts/kc_data_transfer/src/requirements.txt, server/auth_function/requirements.txt, server/backend/requirements-dev.txt, server/backend/requirements.txt
#592 
Batches up the changes from renovate: #603 #596 #588 
Leaving #599 out of this because it causes big problems and is a CI change, not a code change. It updates the terraform module that deploys our database. Needs a lot of investigation and testing.
=> fix: #592 renovate dashboard backend

.github/workflows/sonar.yml, .gitignore, server/auth_function/.coveragerc, server/auth_function/lambda_function.py
Testing for SonarCloud coverage.
=> ci: coverage for main merge

.github/workflows/sonar.yml, server/auth_function/.coveragerc
Part two of working on SonarCloud reports for the Auth Function.  Part one handled the main merge in #664.
Using this configuration, here's what happened when the lambda function was duplicated (purposefully bad).
=> ci: #87 coverage for PRs

server/backend/requirements.txt
Reverts bcgov/nr-forests-access-management#633
=> chore(deps): update dependency fastapi to v0.98.0

renovate.json
Local repo control for max concurrent Renovate dependency PRs.
More settings here.  We're using self-hosted.
https://docs.renovatebot.com/self-hosted-configuration/
=> ci: renovate prConcurrentLimit=3

infrastructure/server/oidc_clients_forest_client.tf
- added redirect urls for forest client test and prod refs: #726
=> feat: #726 Added redirect urls for forest client test and prod in terraform

server/auth_function/requirements.txt, server/backend/requirements.txt
Combined update of dependencies done manually since doing separately by renovate doesn't work.
=> chore(deps): update dependency botocore to v1.31.23 and boto3 to v1.28.23

.github/workflows/dev_deployment.yml
Previously was disabled for BCSC integration needs. Now enabled again.
=> fix: Enable dev deployment for push on main.

.github/workflows/sonar.yml
New action release to solve an issue @basilv reported.
=> ci: bump bcgov-nr/action-test-and-analyst to v0.0.2

frontend/src/tests/ProtectedLayout.spec.ts
Fixing error on file ProtectedLayout.spec.ts which breaks the pipeline build for the frontend.
=> fix: #800 Frontend test breaks the pipeline build

frontend/package-lock.json, frontend/package.json, frontend/src/alltypes.d.ts, frontend/src/assets/styles/styles.scss, frontend/src/components/common/Icon.vue, frontend/vite.config.ts
- update frontend dynamic import icons to only import the icons we used refs: #814
=> fix: #814 update dynamic icon import to fix pipeline slow issue

frontend/src/components/common/ProfileSidebar.vue
* fixed logout causing a type error leading to browser error overflow.
=> fix: #827  logout causing type error

frontend/src/components/dashboard/Dashboard.vue
Clearing notification in dashboard `onUnmounted` hook.
=> fix: #826 clear previous success message on dashboard

server/backend/api/app/routers/router_application.py, server/backend/api/app/routers/router_user_role_assignment.py, server/backend/api/app/utils/audit_util.py, server/backend/requirements.txt, server/backend/testspg/authorization/test_jwt_validation.py
- fix audit event type for remove user role access #805
- fix pipeline error cased by FastAPI sub dependency package version change #858 
Update FastAPI package version to 0.100.0. The latest 0.103.0 version just launched a few days ago, feel it's okay to stay on v0.100.0 for now.
=> fix: #858 upgrade fastapi version to solve pipeline issue

frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/SummaryCard.vue
- GrandAccess and SummaryCard are now using our reusable Button component
- Button is showing correct label when loading and when loading finished
=> fix: #719 use same button component

frontend/src/components/common/Button.vue, frontend/src/components/common/ProfileSidebar.vue, frontend/src/enum/IconEnum.ts
- fixed user name disappearing when log out was clicked
- button now have loading state
- button refactored to use our reusable button component
=> fix: #848 user name disappearing when log out

infrastructure/server/oidc_clients_silva.tf
- add user email return to silva application refs: #867
=> fix: #867 add user email return to silva application

infrastructure/server/oidc_clients_fom.tf, infrastructure/server/oidc_clients_forest_client.tf, infrastructure/server/oidc_clients_silva.tf, infrastructure/server/oidc_clients_spar.tf, terraform/dev/terragrunt.hcl, terraform/prod/terragrunt.hcl, terraform/test/terragrunt.hcl, terraform/tools/terragrunt.hcl
- fix url of oidc debugger tool refs: #867
According to our last chat with Marco https://chat.developer.gov.bc.ca/channel/sso/thread/YEkEMBFZngu93N83w, they changed the url of OIDC debugger tool
=> fix: #867 fix url of oidc debugger tool 

frontend/src/components/Landing.vue, frontend/src/components/common/Button.vue, frontend/src/components/common/ProfileSidebar.vue, frontend/src/components/dashboard/Dashboard.vue, frontend/src/components/dashboard/UserDataTable.vue, frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/Summary.vue, frontend/src/components/grantaccess/SummaryCard.vue, frontend/src/components/header/Header.vue, frontend/src/services/http/HttpCommon.ts, frontend/src/store/LoadingState.ts
- Fix/Remove unnecessary try-catch in components.
- Organize some import using better reference.
- Create LoadingState store for central loading.
- Trigger "startLoading", "stopLoading" and "stopLoadingOnError" at both new request/response HttpInterceptors.
- Add loadingLabel at Button component and implement feature for Button to take care of label change when loading.
=> fix: #874 frontend improvement no try catch

.github/workflows/reusable_terraform_frontend.yml, .github/workflows/reusable_terraform_server.yml
Fix previous action swap is having old action appended.
=> fix: incorrect swapped action

infrastructure/server/oidc_clients_spar.tf
=> fix: update redirect url for spar as requested

frontend/src/components/grantaccess/GrantAccess.vue
Previous merge broke the frontend build by making a disabled bind to a variable that could be undefined. This fix solves this issue.
=> fix: broken frontend build from previous merge

frontend/src/components/grantaccess/GrantAccess.vue
=> fix: #999 fix the role not render problem on the grant access page

frontend/src/assets/styles/layout.scss, frontend/src/components/managePermissions/UserDataTable.vue
- Changed default paginator to 50 pages
-
=> fix: #953 paginator default page

frontend/src/router/index.ts
- Breadcrumb now show the current route
https://app.zenhub.com/workspaces/fsa-fingerprint-61f04f08304d3e001a4f2578/issues/gh/bcgov/nr-forests-access-management/995
=> fix: #995 current route on breadcrumb

frontend/src/components/common/ProfileSidebar.vue, frontend/src/components/header/Header.vue
- fixed white spaces caused by using primevue button styles
- added cursor pointer to profile toggle button
=> fix: #997 frontend small fixes

frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/StepContainer.vue
=> fix: #1020 fix grant access page role change issue

frontend/src/components/grantaccess/ForestClientCard.vue, frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/StepContainer.vue
=> fix: #1020 fix forest client number add error

infrastructure/server/oidc_clients_spar.tf
=> fix: #984 added to return login user email for SPAR

frontend/src/store/NotificationState.ts
- fixed wrong typing breaking main
=> fix: typing breaking build

frontend/src/components/common/NotificationMessage.vue, frontend/src/components/common/PageTitle.vue, frontend/src/components/common/ProfileSidebar.vue, frontend/src/components/common/SideNav.vue, frontend/src/components/grantaccess/ForestClientCard.vue, frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/UserIdentityCard.vue, frontend/src/components/header/Header.vue, frontend/src/components/managePermissions/ManagePermissions.vue, frontend/src/components/managePermissions/ManagePermissionsTitle.vue, frontend/src/components/managePermissions/UserDataTable.vue
- refactor the frontend component code, to define function in a consistent way
- adjust the import statement, always put external import at the top
- auto format the component files
- cleanup unused code
- group the methods in grant access component based on form field
=> refactor:  #1022 refactor frontend code to be consistent

frontend/package-lock.json, frontend/package.json, frontend/src/alltypes.d.ts, frontend/src/components/common/Icon.vue, frontend/src/components/common/NotificationStack.vue, frontend/src/components/header/Header.vue, frontend/src/components/managePermissions/ManagePermissions.vue, frontend/src/components/managePermissions/TablePlaceholder.vue, frontend/src/components/managePermissions/UserDataTable.vue
- Implementation of primevue tab component
- Delegated admin tab is disabled until the respective table is available
- The styling is on the common repo
=> feat: #850 primevue component tab

frontend/src/store/BreadcrumbState.ts
Thanks Catherine. This was missed.
=> fix: #1097 fix import error due to refactoring.

frontend/package-lock.json, frontend/package.json
update primevue to v3.40.0, the latest version is too new.
=> fix: (frontend) update primevue and custom stylesheet version

infrastructure/server/oidc_clients_spar.tf
As required by Spar, refs: #1122
=> feat: #1122 support spar to add dev redirect urls to test

infrastructure/server/oidc_clients_forest_client.tf
=> fix: #1134 add test logout url for forest client test

frontend/src/components/managePermissions/ManagePermissions.vue, frontend/src/components/managePermissions/table/ApplicationAdminTable.vue, frontend/src/components/managePermissions/table/DelegatedAdminTable.vue, frontend/src/components/managePermissions/table/UserDataTable.vue, frontend/src/layouts/ProtectedLayout.vue, frontend/src/router/index.ts, frontend/src/router/routeHandlers.ts, frontend/src/services/AuthService.ts, frontend/src/services/fetchData.ts, frontend/src/static/sideNav.json, frontend/src/store/Constants.ts, frontend/src/store/FamLoginUserState.ts
- New table showing delegated admins
- New Tab for delegated admins
- Using API https://github.com/bcgov/nr-forests-access-management/issues/1086 to populate the table
- Only app admin have delegated admin management functionality.
=> feat: #1149 delegated admin table screen

frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/GrantApplicationAdmin.vue, frontend/src/components/grantaccess/GrantDelegatedAdmin.vue, frontend/src/components/grantaccess/form/RoleSelect.vue, frontend/src/components/managePermissions/ManagePermissions.vue, frontend/src/components/managePermissions/table/DelegatedAdminTable.vue, frontend/src/router/index.ts, frontend/src/router/routeHandlers.ts, frontend/src/router/routeItem.ts, frontend/src/services/utils.ts, frontend/src/store/Constants.ts, frontend/src/store/FamLoginUserState.ts, frontend/src/views/GrantDelegatedAdminView.vue
- Created `GrantDelegatedAdmin` and `GrantDelegatedAdminView` components;
- Getting the app role list from the cached user accesses;
- Validating required fields before submit button is enabled;
- Created new new path to delegated admin page route;
- Only FAMMake sure only app admin can access to this route
=> feat: #1159 add delegated admin form

frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/form/RoleSelect.vue, frontend/src/router/index.ts, frontend/src/router/routeHandlers.ts, frontend/src/services/AuthService.ts, frontend/src/services/fetchData.ts, frontend/src/store/FamLoginUserState.ts
- switch from using api call to using cache information
- removed roles attribute from FamLoginUser
- removed unused fetchApplicationRoles
=> feat: #1147 get list of roles from cache

server/flyway/sql/V41__add_client_role_admin.sql
refs: #1256
- Add new Forest Client role, CLIENT_ADMIN
this branch is based on v1.12.2, and once merged to the hotfix branch, release please will trigger a hotfix release v1.12.3
=> fix: #1256 add client role admin

frontend/package-lock.json, frontend/package.json
still need this package, put it back, and install the latest version
=> chore(deps): replace dependency npm-run-all with npm-run-all2 ^5.0.0

frontend/src/components/grantaccess/GrantAccess.vue, frontend/src/components/grantaccess/GrantApplicationAdmin.vue, frontend/src/components/grantaccess/GrantDelegatedAdmin.vue
- change button wording in GrantAccess to "Grant Access".
- change button wording in GrantApplicationAdmin to "Create Delegated Admin".
- change button wording in GrantDelegatedAdmin  to "Create Application Admin".
=> feat: #1126 Change button wording

server/flyway/sql/V44__update_client_app_name.sql
refs: #1236 
Update application description of Forest Client
=> fix: #1236 update client app name

frontend/package-lock.json, frontend/package.json, frontend/src/assets/styles/styles.scss, frontend/src/components/grantaccess/GrantDelegatedAdmin.vue, frontend/src/components/managePermissions/ConfirmDialogText.vue
- added question sign
other styling is on common repo.
=> fix: #1191 Confirmation popup has too many white space

frontend/src/components/managePermissions/table/DelegatedAdminTable.vue
- fixed sorting on the delegated admins tables
=> fix: #1263 Sort role in delegated admin table is not working

.github/workflows/sonar.yml
Solved by @MCatherine1994.  Glory stolen by me.  :P
=> fix(ci): sonarcloud versions

frontend/src/components/myPermissions/MyPermissionsTable.vue, frontend/src/store/FamLoginUserState.ts
Styling changes on my permissions view. https://github.com/bcgov/nr-forests-access-management/pull/1276
- env column closes to application name
- placeholder text
- removed env from application name
=> feat: #985 minor table styling tweaks

frontend/src/components/myPermissions/MyPermissionsTable.vue, frontend/src/store/FamLoginUserState.ts
- Fixed pipeline build error caused by missing type on getMyAdminPermission function on https://github.com/bcgov/nr-forests-access-management/pull/1308
=> fix: 985 frontend pipe line fix

server/admin_management/api/app/constants.py, server/admin_management/api/app/services/access_control_privilege_service.py, server/admin_management/api/app/services/application_admin_service.py, server/admin_management/api/app/utils/utils.py, server/backend/api/app/constants.py, server/backend/api/app/crud/crud_application.py, server/backend/api/app/crud/crud_user_role.py, server/backend/api/app/crud/crud_utils.py, server/backend/api/app/routers/router_application.py, server/backend/api/app/routers/router_guards.py, server/backend/api/app/schemas.py, server/backend/api/app/utils/utils.py, server/backend/requirements-dev.txt, server/backend/testspg/conftest.py, server/backend/testspg/crud/test_crud_application.py, server/backend/testspg/router/test_router_application.py, server/backend/testspg/router/test_router_user_role_assignment.py, server/flyway/local_sql/sample_V1002__add_local_user_cognito_id.sql
#1184 
- Add filter for get_user_role_assignment method to allow BCeID user only see records from the same organization.
- Add filter for get_user_role_assignment method to restrict to the roles/forest-clients that the delegated administer has privilege to grant.
- Add pytest-asyncio Python package to support async pytests.
- Create 'get_current_requester_by_token' helper fixture to fix broken tests due to get_user_role_assignment method change.
- Adjust one of the 'cognito_user_id' for sample local flyway.
- Added back Requester's "access_roles" attribute as it is needed for determine if requester is app admin.
Will create another branch to work on tests.
=============================================================
May not be that details but added some hand testing screenshots.
* APP …
=> feat: #1184 delegated admin filtering same org

frontend/src/layouts/ProtectedLayout.vue
=> fix: #1317 fix frontend build type error caused by sidenav

server/backend/api/app/routers/router_guards.py, server/flyway/sql/V48__update_bceid_description.sql
=> fix: #1306 fix description for user type code B

server/backend/api/app/database.py
=> fix: #1338 add log for debugging db session connection

frontend/src/tests/UsernameInput.spec.ts
- Fixed typing errors in our test suite that were preventing successful builds
=> fix:  Resolved Typing Errors in Tests to Enable Successful Build on pr #1351

frontend/package-lock.json, frontend/package.json, frontend/src/assets/styles/layout.scss
- changed table border radius to match tab component
ref: #1371
=> fix: #1371 tab component not showing on mobile screen size

frontend/src/components/grantaccess/GrantAccess.vue
=> fix: #1421 Enable verifying forest client number as API problem solved

frontend/src/components/Landing.vue, frontend/src/components/managePermissions/ManagePermissions.vue, frontend/src/layouts/ProtectedLayout.vue, frontend/src/router/routeHandlers.ts, frontend/src/services/EnvironmentSettings.ts
refs: #1464
Hide delegated admin features for TEST, TOOLS and PROD environments, as we're not ready to deploy that for user to see yet.
=> fix: # 1464 Hide delegated admin features for non-dev environments

infrastructure/server/oidc_clients_silva.tf, infrastructure/server/oidc_clients_spar.tf
=> fix: #1459 #1461 Add redirect urls for SPAR and SILVA

frontend/src/components/grantaccess/form/UserNameInput.vue, frontend/src/store/ApplicationState.ts
=> fix: #1481 Fix application env parameter undefined error

frontend/src/components/managePermissions/table/ApplicationAdminTable.vue, frontend/src/components/managePermissions/table/DelegatedAdminTable.vue, frontend/src/components/managePermissions/table/UserDataTable.vue
=> feat: #1115 Display user information in table

server/admin_management/api/app/constants.py, server/backend/api/app/constants.py
=> fix: #1487 Fix typo of AWS target environment variable

server/backend/api/app/integration/bcsc/bcsc_jwk.py
ref: #1454 
* Remove code dependency to 'jose' for AESKey.
=> fix: #1454 Remove jose dependency

infrastructure/server/oidc_clients_spar.tf
=> fix: #1503 Add redirect url for spar

server/backend/api/app/crud/crud_user.py
=> fix: #1521  fix one-time load user information logic

.github/workflows/reusable_data_model_gen.yml
=> feat: #1031 Enable SchemaSpy to auto generate data model

.github/workflows/prod_deployment.yml, .github/workflows/reusable_data_model_gen.yml
=> feat: #1031 Fix SchemaSpy pipeline and auto run when do prod deployment 

.github/workflows/dev_deployment.yml, .github/workflows/prod_deployment.yml
=> fix: #1031 Fix SchemaSpy trigger in production deployment yaml

server/flyway/local_sql/sample_V1002__add_local_user_cognito_id.sql
Add Craig to our local user setup script, so he can copy this file locally and get his user record on local.
=> fix: Add new user to local setup script

infrastructure/server/oidc_clients_fam.tf, infrastructure/server/oidc_clients_fom.tf, infrastructure/server/oidc_clients_forest_client.tf, infrastructure/server/oidc_clients_silva.tf, infrastructure/server/oidc_clients_spar.tf, infrastructure/server/variables_provided.tf, terraform/dev/terragrunt.hcl, terraform/prod/terragrunt.hcl, terraform/test/terragrunt.hcl, terraform/tools/terragrunt.hcl
Closes: #1509 
- Replaced old OIDC debugger url with playground url
=> fix: #1509 Replace OIDC SSO playground url

frontend/src/components/UserSummaryCard/index.vue, frontend/src/utils/UserUtils.ts
Added a new user util function to format a user's full name
=> fix: #1540 add dashes to null name

frontend/src/components/grantaccess/form/UserNameInput.vue
- prevents users looking themselves up
- automatically verify user ID on blur
=> fix: #1436 prevent self lookup on grant access

frontend/src/components/managePermissions/table/UserDataTable.vue
=> fix: remove disable logic

frontend/src/components/UserPermissionHistoryTable/index.vue, frontend/src/components/managePermissions/table/DelegatedAdminTable.vue, frontend/src/components/managePermissions/table/UserDataTable.vue, frontend/src/components/managePermissions/table/utils.ts, frontend/src/views/UserDetails/index.vue
- renamed user history page title
- separated the navigate logic out in its a util file
- added the icon button on d-admin's action col
=> feat: #1619 add user history icon to d amin action column

infrastructure/server/oidc_clients_silva.tf
=> fix: #1653 add new callback and sign-out urls for silva

frontend/src/assets/styles/layout.scss, frontend/src/layouts/ProtectedLayout.vue, frontend/src/router/index.ts
=> fix: #1665 prod release fixes

frontend/src/constants/Notifications.ts, frontend/src/views/AddAppPermission/index.vue, frontend/src/views/AddFamPermission/index.vue
=> fix: #1673 add IDIM warn notification message

frontend/src/components/AddPermissions/RoleSelectTable.vue, frontend/src/components/AddPermissions/UserIdentityCard.vue, frontend/src/components/ManagePermissionsTable/index.vue, frontend/src/views/AddAppPermission/index.vue, frontend/src/views/ManagePermissionsView/index.vue, frontend/src/views/ManagePermissionsView/utils.ts
Closes #1685
style fix and wording fix
=> fix: #1685 style fixes on add/manage permission pages

frontend/src/components/ManagePermissionsTable/index.vue
Quick fix to add default size to frontend to query more than 50 items from backend.
=> fix: Quick fix to add default size to frontend to query more than 50 items from backend.

server/admin_management/api/config/config.py, server/backend/api/config/config.py
=> fix: #1711 clear-text logging of sensitive information

frontend/src/components/AddPermissions/UserIdentityCard.vue, frontend/src/components/ManagePermissionsTable/utils.ts
- Add sortyBy param for "email".
=> fix: Add email for "soryBy" param in request.

frontend/src/components/UserSummaryCard/constants.ts, frontend/src/components/UserSummaryCard/index.vue, frontend/src/layouts/SideNav.vue, frontend/src/store/SideNavState.ts, frontend/src/store/screenSizeState.ts
ref: #1732 ,
- Fix User Summary margin for fields for small device.
- Fix sideNav to be able to hide after items are clicked on small device.
This is temporarily deployed to https://fam-dev.nrs.gov.bc.ca/, can be verified using DEV environment.
=> fix: #1732 Frontend responsiveness adjustment

server/admin_management/api/app/integration/gc_notify.py
ref: #1746 
- Minor adjustment to reflect the template adjustment.
=> fix: #1746 Adjust parameters for email template adjustment.

server/auth_function/lambda_function.py, server/auth_function/test/lambda_function_test.py
Update auth function to stop updating business_guid for existing users (since the attribute might be missing).
Also have the auth function update the update_user/update_date audit columns.
=> fix: #1754 Missing business_guid

server/backend/api/app/crud/crud_user.py, server/backend/api/app/schemas/fam_user_update_response.py
Verify the existing user information update endpoint is still good to run.
Minor adjustment to the method.
Will use this endpoint to update users records to fix data issue for #1754.
=> fix: #1754 User info update endpoint minor adjustment

frontend/public/env.json, frontend/src/aws-exports.js, terraform/common_vars.hcl
Another fix attempt - dev specific.
=> fix: #1773 keycloak logout

infrastructure/server/oidc_clients_apt.tf
ref: #1794 
Jazz requested to update APT callback urls.
- Callback urls updated at Terraform for APT client for all environments.
=> chore: #1794 Update apt callback urls

server/flyway/CONVENTION.md, server/flyway/sql/V64__update_apt_app_role_name.sql
ref: #1802 
- Adjust APT role name to be consistent with other applications. 
VIEWER -> APT_VIEWER
EDITOR -> APT_EDITOR
- Add a initial markdown for database convention.
=> fix: #1802 Update role name for apt

infrastructure/server/oidc_clients_apt.tf
ref: #1818 
* add additional callback url to app cliant APT on TEST.
=> fix: #1818 Callback url addition for APT in test.

frontend/src/aws-exports.js, infrastructure/server/oidc_clients_fom.tf
ref #1821 
- Adjust FOM TEST callback url due to change of using default OpenShift route.
=> fix: 1821 fom callback url change

frontend/src/views/LandingView/index.vue
- Add service unavailable message at FAM landing page. Temporary message for SSO login instability.
=> fix: Add service unavailable message.

frontend/src/views/LandingView/index.vue
Login issue due to SSO problem is resolved. FAM is working again.
- Remove previous landing page service interrupt message.
=> fix: Remove service interruption warning

frontend/package-lock.json, frontend/package.json
fix dependabot warnings: https://github.com/bcgov/nr-forests-access-management/security/dependabot/206, https://github.com/bcgov/nr-forests-access-management/security/dependabot/204, https://github.com/bcgov/nr-forests-access-management/security/dependabot/203, https://github.com/bcgov/nr-forests-access-management/security/dependabot/200, https://github.com/bcgov/nr-forests-access-management/security/dependabot/194, https://github.com/bcgov/nr-forests-access-management/security/dependabot/185, https://github.com/bcgov/nr-forests-access-management/security/dependabot/184
=> fix(deps): #1839 Update vite related packages for frontend

server/flyway/sql/V65__add_suspend_role_to_forest_client_prod.sql, server/flyway/sql/V66__add_admin_role_to_fom.sql
- Add role "Suspend" for CLIENT_PROD
- Add role "Admin" for FOM_DEV and FOM_TEST
=> feat(flyway): #1855,#1857 Added role for fam clients

infrastructure/server/flyway.tf
Sorry, missed it.
- fix missing comma
=> fix: 1880 fix flyway terraform missing comma

infrastructure/server/flyway.tf
=> fix: fix another comma

.github/workflows/lza_ci_infrastructure.yml, .github/workflows/lza_reusable_terraform_server.yml, lza-infrastructure/terraform/server/auth_lambda.tf, lza-infrastructure/terraform/server/oidc_clients_forest_client.tf, lza-infrastructure/terraform/server/oidc_idp_bcsc.tf, lza-infrastructure/terraform/server/user_pool.tf, lza-infrastructure/terraform/server/variables_provided.tf
Quick merge to include auth-lambda and bcsc configuration.
=> feat: #1917 lza migration auth-lambda and bcsc

.github/workflows/lza_test_deployment.yml, .github/workflows/lza_test_destruction.yml, lza-infrastructure/landing-zone/frontend/dev/terragrunt.hcl, lza-infrastructure/landing-zone/frontend/test/terragrunt.hcl, lza-infrastructure/landing-zone/server/test/terragrunt.hcl
Initial configuration for LZA TEST environment:
- Workflow for LZA TEST.
- Terragrunt for LZA TEST.
=> feat: #1950 LZA TEST Workflow and Terragrunt Configuration.

.github/workflows/reusable_data_model_gen.yml, docker-base-services.yml, infrastructure/server/flyway.tf, infrastructure/server/oidc_clients_waste_plus.tf, lza-infrastructure/terraform/server/flyway.tf, lza-infrastructure/terraform/server/oidc_clients_waste_plus.tf, server/flyway/sql/V68__create_waste_plus_application_roles.sql
ref: #1944 
Onboarding Waste_Plus application to FAM, for all environments:
* V68 flyway script - Add Waste Plus application and roles to FAM and app client IDs to fam_application_client.
* infrastructure/../flyway.tf: add `[env]_waste_plus_oidc_client` parameter for flyway placeholders.
* lza-infrastructure/../flyway.tf: add `[env]_waste_plus_oidc_client` parameter for flyway placeholders.
* Add Cognito OIDC clients for waste_plus application.
=> feat: #1944 WASTE PLUS App Onboarding to FAM

server/flyway/sql/V69__add_admin_role_to_fom_prod.sql
Add 'Admin' role for FOM to PROD environment.
=> feat: #1972 FOM PROD admin role

infrastructure/server/oidc_clients_waste_plus.tf, lza-infrastructure/terraform/server/oidc_clients_waste_plus.tf
Waste Plus application redirect url adjusted:
- Dev Cognito Client, append "**-frontend**" after pr number.
=> feat: #1976 Adjust Wast redirect url

server/flyway/sql/V70__add_prod_ilcr_application_roles.sql
ref: #1987
- ILCR_PROD added to FAM.
- ILCR_ADMIN and ILCR_SUBMITTER roles added for ILCR_PROD.
- Add cognito client id for ILCR_PROD.
=> feat: #1987 Flyway to add new ILCR_PROD and roles.
