- server/backend/api/app/routers/router_application.py
* trying additional decorators based on this idea:
https://stackoverflow.com/questions/71984078/fastapi-application-as-an-aws-lambda-function-url-gets-stuck-in-eternal-redirect
> fix: mangum/router connectivity

- frontend/index.html
- frontend/src/App.vue
- frontend/src/aws-exports.js
- frontend/src/main.ts
- frontend/src/services/AuthService.ts
This is for ticket #386.
From observations, this initial blank page only happens during user's "**first time**" (particularly when no browser caching from previous loading) accessing the FAM site.
Found that web browser stack can use "**preload**" for preloading some content for **performance** and that seems to solve the problem. Tested few times on browsers (Chrome/Edge) with clear caching and inPrivate mode, I observed it is consistent now with no blank page issue.
> 386-init-app-blank-page

- frontend/src/components/SelectApplication.vue
- frontend/src/services/ApplicationState.ts
- frontend/src/services/AuthService.ts
- frontend/src/services/ErrorService.ts
- frontend/src/services/http/HttpCommon.ts
- frontend/src/services/http/HttpResponseInterceptors.ts
- server/backend/api/app/crud/crud_utils.py
- server/backend/api/app/jwt_validation.py
- Fix logic error (conflict with naming) for "isApplicationSelected" state usage.
- Adjust ErrorService so it can log Axios errors (using "isAxiosError") and also log common javascript errors.
- Separate 401 and 403 responses into two interceptors.
- Use "info" level for logging at backend to prevent confusion for real error.
> #399 Fix loading errors

- server/backend/api/app/constants.py
- server/backend/api/app/crud/crud_forest_client.py
- server/backend/api/app/crud/crud_role.py
- server/backend/api/app/crud/crud_user.py
- server/backend/api/app/crud/crud_user_role.py
- server/backend/api/app/jwt_validation.py
- server/backend/api/app/routers/router_user_role_assignment.py
- server/backend/tests/crud/test_crud_user_role_assignment.py
- server/flyway/sql/V22__create_and_update_user_length_increase.sql
This PR contains:
- extracts "username" from access_token claim as a requester to API. This is Cognito's user id.
- obtains "requester" (username) as router "Depends".
- saves API requester into db various tables' create_user field.
- Flyway script v22 to increase create_user/update_user length for saving this Cognito user id.
> Feat/367 save user (API Requester) with cognito user

- .github/workflows/reusable_auth_function_ci.yml
- docker-compose.yml
- infrastructure/server/flyway.tf
- infrastructure/server/oidc_clients_spar.tf
- server/backend/testspg/crud/test_crud_application.py
- server/flyway/sql/V23__create_spar_application.sql
- onboard spar, create spar oidc client in terraform
- add spar application, application client for all env, spar admin role for all env, and two testing roles "user_write" and "user_read" (got from SPAR team) for all env in db
- update flyway infrastructure to pass cognito spar client id
- update pipeline and docker-compose to put flyway placeholder for the spar client id, just random strings
- update the test that gets all applications, update the asset number when we add apps
> Feat/453: Onboard SPAR

- infrastructure/server/flyway.tf
Found out the hard way that the name of the s3 bucket has to be unique across the entire BC Government account. Randomized the name.
> fix: 438 flyway scripts bucket name unique

- infrastructure/server/aurora-v2.tf
- upgrade aurora postgres version from 13.6 to 13.9 refs: #517
- disable auto minor version upgrade
> fix: #517 Spike aurora-postgresql version auto upgraded by AWS

- server/backend/api/app/constants.py
- server/backend/api/app/crud/crud_role.py
- server/backend/api/app/crud/crud_user_role.py
- server/backend/tests/tests/crud/test_crud_role.py
- server/backend/tests/tests/crud/test_crud_user_role_assignment.py
- server/backend/tests/tests/fixtures/fixtures_crud_application.py
- server/backend/tests/tests/fixtures/fixtures_crud_forestclient.py
- server/backend/tests/tests/fixtures/fixtures_crud_role.py
- server/backend/tests/tests/fixtures/fixtures_crud_user.py
- server/backend/tests/tests/fixtures/fixtures_crud_user_role_assignment.py
- server/backend/tests/tests/router/test_router_userRoleAssignment.py
- server/backend/tests/tests/test_constants.py
This PR is to fix bug described in #516.
* The bug is identified as a wrong query result on crud_role.get_role_by_role_name(), which is missing one more filtering parameter (application_id) as now FAM role is environment(application) specific (dev/test/prod).
* Previous FAM fam_role table had initial unique constraint as (role_name) only. Then some time ago, this constraint is updated to (role_name, application_id) after FAM has multiple application environments(such as fom_dev/fom_test/fom_prod) for each FAM environment and the function was missed to upgrade along that change.
> fix: #516 Duplicate and Environment Conflict when Creating Role Assignment in PROD for FOM TEST for Client

- infrastructure/server/oidc_clients_fom.tf
- infrastructure/server/oidc_clients_spar.tf
- infrastructure/server/outputs.tf
- infrastructure/server/variables_provided.tf
- terraform/common_vars.hcl
- terraform/dev/terragrunt.hcl
- terraform/prod/terragrunt.hcl
- terraform/test/terragrunt.hcl
The PR fixes logout_chain_url not matching with Cognito app clients environments ([app]_dev, [app]_test, [app]_prod)
* Migrate common logout chain urls (Cognito app client env specific) to common_vars.hcl.
* Setup terragrun "cognito_app_client_logout_chain_url" var as a map so oidc app client can reference to it with environments(dev, test, prod)
* Use "local.common_vars.inputs.idp_logout_chain_dev_url" to make values DRY on each environment's setting.
* Make sure oidc_client_fom.tf/oidc_client_spar.tf use environment specific value for dev/test/prod
> fix: #519 fam cognito logout for fom TEST not working

- .github/workflows/sonar.yml
- server/auth_function/.coveragerc
- server/auth_function/lambda_function.py
- server/backend/.coveragerc
Sonar Clould isn't generating coverage for auth. This is confusing, because coverage appears to be picked up.
From Sonar run:
```
INFO: Python test coverage
INFO: Parsing report '/github/workspace/server/auth_function/coverage.xml'
```
Small adjustment made, since an error was coming from relative_files in .coveragerc in the [report] section.
```
.venv/lib/python3.11/site-packages/coverage/config.py:324: CoverageWarning: Unrecognized option '[report] relative_files=' in config file .coveragerc
warn(
...
```
Update: Working!  Combination of .coverragerc and sonar params.
> ci: adjust sonar for auth

- frontend/package-lock.json
- frontend/package.json
Bumps [fast-xml-parser](https://github.com/NaturalIntelligence/fast-xml-parser) to 4.2.7 and updates ancestor dependency [aws-amplify](https://github.com/aws-amplify/amplify-js). These dependencies need to be updated together.
Updates `fast-xml-parser` from 4.1.3 to 4.2.7
- [Release notes](https://github.com/NaturalIntelligence/fast-xml-parser/releases)
- [Changelog](https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/CHANGELOG.md)
- [Commits](https://github.com/NaturalIntelligence/fast-xml-parser/compare/v4.1.3...v4.2.7)
Updates `aws-amplify` from 5.2.2 to 5.3.6
- [Release notes](https://github.com/aws-amplify/amplify-js/releases)
- [Changelog](https://github.com/aws-amplify/amplify-js/blob/main/docs/changelog.md)
- …
> chore(deps): bump fast-xml-parser and aws-amplify in /frontend

- frontend/src/assets/styles/layout.scss
- frontend/src/components/grantaccess/GrantAccess.vue
- Don't hide next button on grant access page, just disable it for form validation.
- Minor adjustment for spacing at the bottom.
> fix: #759 Show Next button in the grant access page, but disabled it until meet requirement.

- .github/workflows/sonar.yml
- .gitignore
Update bcgov-nr/action-test-and-analyse to v1.0.0.  This adds triggers so tests can be run only if certain folders are changed.  JS/TS only for now.
> ci: update and triggers for frontend tests

- frontend/src/components/grantaccess/Summary.vue
- frontend/src/services/http/HttpCommon.ts
- frontend/src/services/http/HttpResponseInterceptors.ts
When self-granting error or any 403 error happens, app should stay on the same page and not redirect to the Dashboard.
Previously, there was a Http response interceptor that redirected all 403 errors to the Dashboard. This interceptor has been removed, so the user stays at the page that originated the 403 error.
> fix: #825 403 error interceptor

- server/backend/readme.md
- server/backend/requirements-dev.txt
- server/backend/requirements.txt
Freeze two important dependencies (app uses these) version, so they are consistent for installation on different systems to prevent breaking version installation for some local development.
Based on Catherine's working local version:
pydantic==1.10.4
SQLAlchemy==1.4.41
Also commit a branch for fixes for both dependencies on V2: fix/backend-dependencies-fix-pydantic2-sqlalchemy2
> fix: Freeze important pydantic and SQLAlchemy dependencies version.

- infrastructure/server/oidc_clients_fam.tf
- infrastructure/server/oidc_clients_silva.tf
We need to make the user attributes both readable and writable in order to let Cognito update the user record and return the information back to the application, #720
> fix: #720 make user attribute displayname and email writable 

- frontend/src/assets/styles/default-theme.scss
- frontend/src/components/grantaccess/UserIdentityCard.vue
- user Identity card are now using the new design
some styling is on the common repo.
> feat: #846 user information card new design style

- frontend/package-lock.json
- frontend/package.json
- frontend/src/assets/styles/default-theme.scss
- frontend/src/assets/styles/styles.scss
- frontend/src/components/Landing.vue
- frontend/src/components/common/SideNav.vue
- frontend/src/components/grantaccess/GrantAccess.vue
- frontend/src/components/managePermissions/UserDataTable.vue
- frontend/src/tests/Landing.spec.ts
Fix #897:
- update fontsize in side nav, and change the unit from px to rem
- remove the border radius for the speific add user permission button
- fix user data table background height problem
- update to use the latest nr-theme package
- remove unused class name
Style changes for button on focus is in the shared stylesheet
> fix: #897 frontend minor style changes

- .github/workflows/reusable_terraform_frontend.yml
- .github/workflows/reusable_terraform_server.yml
Deprecations in unmaintained action.
https://github.com/peter-murray/terragrunt-github-action
Replacing with action it was forked from.
https://github.com/autero1/action-terragrunt
Blog about deprecation.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Fail example.
https://github.com/bcgov/nr-forests-access-management/actions/runs/6499302008/job/17652383720#step:10:25
> ci: swap out unmaintained action

- .github/workflows/ci_auth_artifact.yml
- .github/workflows/reusable_terraform_frontend.yml
- .github/workflows/reusable_terraform_server.yml
- .github/workflows/sonar.yml
Node 12 has been deprecated.  Actions using it will stop working when GitHub eventually pulls the plug in their runners.
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
> ci: update checkout action for node 12 deprecation

- .github/workflows/ci_auth_artifact.yml
- .github/workflows/reusable_terraform_server.yml
The warning below is found during most current deployment from Github:
Update the action to v3.
> ci: Update actions/upload-artifact action to v3

- server/backend/api/app/routers/router_guards.py
- server/backend/testspg/router/test_router_application.py
- Add missing type for `application_id` at `router_guards::authorize_by_app_id()` which failed Pythone type check.
- Add test to capture the router response when application_id is an invalid `str` type.
> fix: #987 add missing type check router guards

- server/backend/api/app/crud/crud_user.py
- server/backend/api/app/crud/crud_user_role.py
- server/backend/api/app/integration/idim_proxy.py
- server/backend/api/app/routers/router_idim_proxy.py
- server/backend/api/app/schemas.py
- server/backend/testspg/crud/test_idim_proxy_service.py
- server/backend/testspg/router/test_router_idim_proxy.py
For task #993 
* Align `user_name` and `userId` to max length 20 (frontend already has 20 in max). IDIM doc has the max as 20.
* Changes are on `router_idim_proxy.py` and `schemas.py`, others just some formatting adjustment.
> fix: #993 user name field consistency

- .github/workflows/tools_deployment.yml
- infrastructure/server/admin_management_api_gateway.tf
- infrastructure/server/fam_admin_management_api.tf
- infrastructure/server/oidc_clients_fam.tf
- infrastructure/server/outputs.tf
- terraform/tools/terragrunt.hcl
* A new API `admin_management_api_gateway` Gateway.
* Associate new API gateway with new `fam_admin_management_api` lambda.
* Add api-gateway url to Cognito callbackUrl.
* Prepared terraform "output" for new api url.
success + 200 + 13 ?!! :
> feat: #1010 admin api gateway

- frontend/src/components/common/ToastMessage.vue
- frontend/src/errors/FamCustomError.ts
- frontend/src/router/index.ts
- frontend/src/router/routeHandlers.ts
- frontend/src/router/routeItem.ts
- frontend/src/services/fetchData.ts
- frontend/src/services/utils.ts
- frontend/src/store/ToastState.ts
Add route security and handle route error for toast.
- if user does not login, and tries to access any protected pages, always redirect back to landing page, and show the error message like "you're not login"
- if user login without any role
- ‘/dashboard’, show empty table and the error message something is like “don’t have the necessary authorization for the requested action”
- ‘/grant’, because no application can be selected to grant, redirect to the ‘/dashboard’, the error in dashboard page will show
> fix: #1097 add route security

- server/admin_management/api/app/routers/router_utils.py
Fix one of the import (Session), which was wrong from `requests`, should be from `sqlalchemy.orm`
> fix: fixing wrong import for Session

- frontend/src/components/common/SideNav.vue
- Changing the `SideNav` BC Logo redirect to the Manage Permissions page ('/dashboard')
> fix: #1106 bc logo redirect

- frontend/package-lock.json
- frontend/package.json
- frontend/src/assets/styles/default-theme.scss
- frontend/src/components/common/PageTitle.vue
- Fixed breadcrumb component not routing.
The breadcrumb component now receives the home as a prop, in the primevue breadcrumb component documentation has exemples using the name "`route`" for the the path but the component it self expects "`item.url`". Tried using "`route`" and "`path`" as the `routeItems` object key but it did not work, "`url`" worked though.
https://github.com/primefaces/primevue/commit/ad9b437003e0d3ae26047d2cfd1a6a6ecc9037d7#diff-33bf4bb142b615a34557b44002c2eb3ac4393bd3fa4099aede38fabbf4e5527f
https://primevue.org/breadcrumb/
> fix: #1121 breadcrumb component not routing

- frontend/src/components/grantaccess/GrantAccess.vue
- frontend/src/components/grantaccess/GrantApplicationAdmin.vue
- frontend/src/components/grantaccess/GrantDelegatedAdmin.vue
- frontend/src/components/managePermissions/ManagePermissions.vue
- frontend/src/enum/TabEnum.ts
- frontend/src/layouts/ProtectedLayout.vue
- frontend/src/static/sideNav.json
- frontend/src/store/CurrentTabState.ts
- sidebar item created for delegated admin page;
- navigation to grant delegated admin page from dashboard table button;
- show the delegated admin management functionality only if I'm an app admin (not including FAM admins);
- selecting correct tab in dashboard page after creating a delegated admin or granting a regular user access;
> feat: #1150 navigation to grant delegated admin screen

- server/flyway/sql/V39__add_client_role.sql
refs: #1232
- Remove the old client roles (USER_READ, USER_WRITE) we created when onboarding them to FAM, we just created those two roles for them to play around, they are not in use
- Add a new role "CLIENT_EDITOR"
**Note:** this pr is for a **hotfix release** followed the [hotfix release strategy](https://github.com/bcgov/nr-forests-access-management/wiki/Creating-a-Release#hotfix-releases), so the fix branch [fix/1232-add-client-role](https://github.com/bcgov/nr-forests-access-management/tree/fix/1232-add-client-role) will be merged to a hotfix base branch (based on last release v1.12.0, and it has to be named "hotfix") to trigger release please management for hotfix release. The pr title starts with "fix", so the hotfix release tag will only bump a patch version, become **v1.12.1**, …
> fix: #1232 add flyway script to add a new client role

- infrastructure/server/oidc_clients_forest_client.tf
- server/flyway/sql/V40__add_client_role_viewer.sql
refs: #1247, #1233
This pr is for a hotfix release to adding a new role for FOREST CLIENT, and update their redirect urls. The hotfix release will be v1.12.2
> fix: #1247 #1233 add new client role, update client redirect urls

- frontend/src/services/AuthService.ts
- Fixed sign out bug by adding the missing "await" for the signOut promise, which was not blocking the code to wait for it's result, causing the cached data to be cleared before actually signing out.
> fix: #1224 - Delegated Admin Table Disappears On Sign Out

- frontend/src/router/routeHandlers.ts
- infrastructure/server/outputs.tf
- infrastructure/server/variables_provided.tf
- server/flyway/local_sql/sample_V1001__add_local_user_cognito_id.sql
refs: #1179 
Fix the bug found after deployment to dev:
- added to show a toast error message in the case the login user has no access in FAM
- fix the frontend redirect logout chain url config for environment variables
> fix: #1179 bceid login bug fix

- server/backend/api/app/crud/crud_access_control_privilege.py
- server/backend/api/app/jwt_validation.py
- server/backend/api/app/main.py
- server/backend/api/app/models/model.py
- server/backend/api/app/routers/router_guards.py
- server/backend/api/app/routers/router_user_role_assignment.py
- server/backend/api/app/schemas.py
- server/backend/testspg/authorization/test_authorization.py
- server/backend/testspg/constants.py
- server/backend/testspg/crud/test_crud_access_control_privilege.py
- server/backend/testspg/crud/test_idim_proxy_service.py
- server/backend/testspg/router/test_router_idim_proxy.py
- server/flyway/sql/V43__api_db_user_read_delegated_admin_table.sql
refs: #1217 
- Add read permission to backend api db user to the access_control_privilege table
- Update router guard method to check both token and access control table for general authorization, and authorization for specific application
- Update test
> feat: #1217 backend check both token and access control table for authorization

- server/admin_management/api/app/models/model.py
- server/backend/api/app/models/model.py
- server/flyway/sql/V45__create_and_update_user_length_increase.sql
refs: #1266
Update create_user and update_user length in tables, so business bceid user's cognito_user_id can be inserted as create/update user
`fam_app_environment`, `fam_role_type` and `fam_user_type_code` has no create_user and update_user column
`fam_application_admin` no need to change, cause no bceid can grant application admin, but for consistency, updated it as well.
> fix: #1266 update create_user and update_user length in db

- infrastructure/server/variables_provided.tf
refs: #1272
One of my guess of the bcsc login error, is because of this "Attribute read and write permissions" mapping, it doesn't have the username in it. So if Cognito wants to do something with the username field but has no permission to do so, it might throw the error we got?  But I can't manually add it through the UI, so I wonder if I could just update the terraform to include it and deploy to DEV. The "maximum_oidc_attribute_read_list" and "maximum_oidc_attribute_write_list" are only used by forest client app integration, so it won't impact other apps. I also found out how to configure our AWS DEV cognito, so we can use AWS DEV to verify the bcsc login, no need to deploy to AWS TEST and PROD.
If it doesn't work I'll revert the code back. Again, forest-client-test and …
> fix: #1272 try to add username attribute for mapping

- infrastructure/server/oidc_idp_bcsc.tf
- infrastructure/server/variables_provided.tf
refs: #1272 
Got a pipeline error, seems like "username" is not a valid read/write attribute, revert the code back
Have another guess, noticed that for bceid user in Cognito, their user attributes have a `sub` field, and it is required, but for the test bcsc user, I didn't see a `sub` field in the user attributes. 
And checked our IDP config terraform file, for IDIR and BCEID, we didn't do a username mapping to sub, think Cognito will auto map it, so want to try to remove the username mapping to sub from the BCSC IDP config as well, and see if that brings any difference.
> fix: #1272 revert read write attribute

- frontend/src/components/Landing.vue
- frontend/src/tests/Landing.spec.ts
refs: #1264
- disabled the bceid login button
- skip the bceid login button test
This is only for the prod deployment to hide this functionality
> fix: #1264 disable bceid login button

- frontend/src/components/managePermissions/table/DataTableHeader.vue
fix the table header for delegated admin, we don't want to confuse user for this prod deployment
> fix: fix the table header text for delegated admin

- server/auth_function/lambda_function.py
FOM reports a bceid login issue:
Checked the AWS PROD Cloudwatch Auth Lambda log, found an error for the audit log when try to get the business guid. So comment out the audit log for getting the business guid, we might could use `event["request"]["userAttributes"].get("custom:idp_business_id") `, but want to fix the login issue as soon as possible, will work on the audit log later. 
Tested with my prod business bceid account, and it works fine. So the error could happen when the login user doesn't have a business_guid somehow, we need more investigation on that. Cause we'll need the business_guid for checking organizations later, we expect the business bceid login user should have a business_guid
> fix: bceid login for FOM production login issue

- server/admin_management/api/app/utils/utils.py
refs: #1315
It's still unclear to me why rstrip() doesn't work properly, but changed to another way seems work fine now.
> fix: #1315 fix application name error

- frontend/src/assets/styles/default-theme.scss
- frontend/src/components/common/SideNav.vue
- frontend/src/static/sideNav.json
Adjusting the sidenav list appearance per request:
> fix: adjusting sidenav list for better viewing

- frontend/src/assets/styles/icon.scss
- frontend/src/components/common/ProfileSidebar.vue
- frontend/src/components/header/Header.vue
- changed toggle profile sidebar button styles
- changed profile sidebar width to match SPAR's
- removed "options" text
ref: #1328 
figma: https://www.figma.com/design/uYkTMUe6vlzOPmRpsIQCen/Home-Screens---Development?node-id=609-24869&t=Ms2EdKYAkXrezSgx-0
> fix: #1328 Update profile side bar to match the design in SPAR

- frontend/src/components/grantaccess/GrantAccess.vue
- frontend/src/components/managePermissions/ManagePermissions.vue
- frontend/src/layouts/ProtectedLayout.vue
refs: #1421 
- Disable adding forest client number for abstract role
- Hide creating/managing delegated admin functionalities 
Please note: the tests will fail in the pipeline because Forest Client API is down
> fix: #1421 Disable adding forest client, and hide delegated admin features

- frontend/src/components/grantaccess/ForestClientCard.vue
- frontend/src/components/grantaccess/GrantAccess.vue
- frontend/src/components/grantaccess/GrantDelegatedAdmin.vue
- frontend/src/components/grantaccess/form/ForestClientInput.vue
- frontend/src/components/grantaccess/form/UserNameInput.vue
- frontend/src/components/managePermissions/table/DelegatedAdminTable.vue
- frontend/src/components/managePermissions/table/UserDataTable.vue
- frontend/src/components/myPermissions/MyPermissionsTable.vue
- frontend/src/services/utils.ts
- frontend/src/tests/ForestClientInput.spec.ts
- Removed the subtitle for the Organization Information section, and replace where it says “user’s client id” with “add one or more client numbers”
- After enter username and hit 'enter', the username is verified instead of submitting the form
- Replaced all instances of "Client ID" with "Client number"
- Updated Tests
> fix: #1190 'enter' behaviour on grant access form

- frontend/src/services/AuthService.ts
refs: #1383
Our backend protects our endpoints that only FAM user (has at least one delegated admin or admin role in FAM) can call, otherwise will return an authorization error. So update frontend to only check if user needs accept terms and conditions if the login user is FAM user (has access in FAM).
> fix: #1383 Only check if user needs accept terms and conditions if is FAM user

- server/backend/api/config/config.py
- server/backend/local-dev.env
refs: #1481
Terraform config use lower case to set target_env variable, but the app env in our database is upper case. Need to match them with lower case.
> fix: #1481 Fix target env in backend to match app env with lower case

- .github/workflows/reusable_terraform_server.yml
- .github/workflows/sonar.yml
- server/admin_management/requirements-dev.txt
- server/auth_function/requirements-dev.txt
- server/backend/requirements-dev.txt
Got a pipeline error when working on the pr #1515, all backend tests failed because of the test container cannot start the container from the docker compose file anymore. https://github.com/bcgov/nr-forests-access-management/actions/runs/10271029988/job/28426203492
The cause of the issue is not very obvious. Everything works last week, and started to get this error from this morning. But could related to the way how test container starts the docker, the `docker-compose` command is no longer supported in GitHub Actions. I didn't find any documentation to explain the issue. But the issue could be solved by updating the `testcontainers` version to the latest v4.7.2, and that requires python > 3.9. 
So updated `testcontainers` version to v4.7.2 in backend, admin management and auth lambda …
> fix: Upgrade test container version to fix pipeline issue

- frontend/src/alltypes.d.ts
- frontend/src/components/common/Icon.vue
- frontend/src/components/common/SideNav.vue
- frontend/src/components/managePermissions/table/UserDataTable.vue
- frontend/src/components/managePermissions/userDetails/UserDetails.vue
- frontend/src/layouts/ProtectedLayout.vue
- frontend/src/router/index.ts
- frontend/src/router/routeHandlers.ts
- frontend/src/router/routeItem.ts
- frontend/src/store/BreadcrumbState.ts
- frontend/src/tests/GrantApplicationAdmin.spec.ts
- frontend/src/views/UserDetailsView.vue
ref: #1542 
- Add icon and navigation to the new user details page.
- Adjust breadcrumb.
- Left out SideNav as discussed.
> feat: #1542 User details link and breadcrumb change.

- server/backend/api/app/schemas.py
Application name should have a max length of 100 instead of 35
> fix: adjusted application name's max length to 100 for gc notify schema

- frontend/src/views/AddAppPermission/index.vue
- frontend/src/views/AddFamPermission/index.vue
- server/admin_management/api/app/integration/idim_proxy.py
- server/backend/api/app/integration/idim_proxy.py
- server/backend/testspg/crud/test_idim_proxy_service.py
- server/backend/testspg/router/test_router_idim_proxy.py
WIP...
- This has dependency on pr: https://github.com/bcgov/nr-fam-idim-lookup-proxy/pull/133
> fix: #1675 (b) Temporary fix FAM search IDIR user scenario by switching to 'idir-account-detail` new IDIM-proxy endpoint.

- server/backend/api/app/decorators/forest_client_dec.py
- server/backend/testspg/decorators/test_forest_client_dec.py
- server/backend/testspg/test_data/forest_client_mock_data.py
Ref: #1638 
FAM dev environment has server error because in TEST environment, there are some user/role database records contains forest_client_number that are not valid and is causing the forest_client_dec to fail because it cannot find/search the forest client to update for the client_name.
- Use .get() instead for getting item from python dict to prevent indexing not existing item.
- Update the test to cover this case.
> fix: #1638 Fix updating forest client name error after search when forest client number isn't a valid one. 

- server/backend/api/app/crud/crud_utils.py
- server/backend/api/app/decorators/forest_client_dec.py
- server/backend/testspg/decorators/test_forest_client_dec.py
Fix production only issue for GET fam application role assignments endpoint:
- Remove wrong `FamApplicationSchema` argument from `crud_utils.use_api_instance_by_app` due to this schema does not have field `app_environment` needed.
- Change __post_sync_forest_clients decorator wrapper to use db session to retrieve proper fam application to be able to find the app_environment for production.
-------------------------------
Note:
- Skip tests failure due to impact from the change for now, will add them back.
- If Python is strongly typed, this would be caught earlier.
> fix: #1689 Fam production only - GET fam application role assignments server error

- .github/workflows/reusable_data_model_gen.yml
- .github/workflows/reusable_terraform_frontend.yml
- .github/workflows/reusable_terraform_server.yml
Closes: #1700 
Github runner for the latest is switching and pointing to ubuntu-24.04. This remove several binaries from the image. Terraform deployment is failing by this removal.
- Install Terraform in GH Action workflow.
* This is recreated from #1702 due to branch naming was having trouble with Terraform deployment file code.
> ci: #1700 Fix Github Runners

- infrastructure/frontend/cloudfront.tf
The deployment failed with some Cloudfront Terraform error due to frontend build "dist" structure change (from new pdf files added at previous pr #1719) .
Few fixes at `cloudfront.tf` were included:
- file pattern to include "_ underscore".
- added additional "application/pdf" content type.
- needed to ignore **"files/.terragrunt-source-manifest"** for the Cloudfront site files due to new structure.
> fix: Cloudfront tf deployment error

- infrastructure/server/aurora-v2.tf
ref: #1737 
Due to AWS 13.10 is now unavailable, we have to:
- upgrade postresql engine version from 13.10 to 13.18 (minor).
This version is currently deployed to DEV for testing.
> fix: #1737 AWS RDS postgresql engine version minor patch upgrade

- server/flyway/sql/V59__add_consep_roles_update_spar_roles.sql
ref: #1715 
Flyway V59 is added for db migration:
Update SPAR roles:
- update the display names of the following roles in SPAR: Submitter (Ministry) to Submitter Ministry (Orchard), Submitter (Non-Ministry) to Submitter Non-Ministry (Orchard)
New two SPAR roles:
* role 1:
display_name(column): Submitter (Tree Seed Centre)
role_name (column): SPAR_TSC_SUBMITTER
role_purpose(column): Allow ministry user to access cone and seed processing, testing and inventory management screens in the CONSEP module of SPAR.
* role 2:
display_name(column): Supervisor (Tree Seed Centre)
role_name (column): SPAR_TSC_SUPERVISOR
role_purpose(column): Allow ministry user to access CONSEP administrative screens and perform administrative function such as deletions and unaccepting results.
> chore: #1715 create consep roles update spar roles

- server/flyway/sql/V60__timestamp_columns_consistency.sql
ref: #1647 
The V60 flyway (on previous pr: https://github.com/bcgov/nr-forests-access-management/pull/1722) missed the scenario that for existing `fam_role` table data, some could have null value for `update_date` before updating the column to NOT NULL.
While locally does not have such data, but deployment to DEV failed. I checked the flyway history in DEV, V60 was get recorded in history because it was failed; so I feel we still can change V60 migration script.
- update the `update_date` column value on several table to be safe for flyway before setting column constraint to NOT NULL.
> fix: #1647 Fix migration for backend timestamp columns consistency

- docker-base-services.yml
- infrastructure/server/aurora-v2.tf
#1740 
- adjusted docker db image to `17.4` (although not the same with db version at AWS aurora-postgresql enginer version).
- adjusted `aurora-v2.tf` for:
- engine_version upgrade: 16.6 (from 13.8)
- renamed parameter_group resource name to have just general name (previously was `"famdb_postgresql13"`) and it is hard to change in future.
- used `name_prefix` for parameter_group naming instead of `name` to prevent Terraform error when changing engine family (resource group already exists error).
- adjusted parameter_group engine family to `family = "aurora-postgresql16"` to match engine_version.
> fix: #1740 AWS RDS postgresql engine major version upgrade

- infrastructure/server/aurora-v2.tf
ref: #1740 
Deployment previously encountered error for a flag needs to be set.
This did not happen when experimenting on AWS Tool deployment. Perhaps it was because in Tools space the database was actually removed (although there were still parameter_group...
> fix: #1740Add allow_major_version_upgrade to resolve terraform failure.

- infrastructure/server/user_pool.tf
Previously when troubleshooting Cognito User Pool user attributes missing, we added `custom:id_token` and `custom:access_token` at AWS DEV Cognito User Pool. These custom attributes cannot be deleted from AWS and currently are causing Terraform run failure (https://github.com/bcgov/nr-forests-access-management/actions/runs/13668845435/job/38257696930) at DEV deployment.
After discussion, we decided to:
- add `custom:id_token` and `custom:access_token` to Cognito User Pool to stop the failure but these attributes will not be mapped.
> fix: Add Cognito User Pool custom id and access tokens attributes

- frontend/public/env.json
- terraform/common_vars.hcl
Required due to Keycloak upgrade.
Not setting the idp_token_hint parameter as the OIDC spec says it is recommended but not mandatory. (https://openid.net/specs/openid-connect-rpinitiated-1_0.html).
This is intended to be the smallest change that should work with the upgrade.
> feat: #1773 Change redirect_uri to post_logout_redirect_uri

- .github/workflows/ci_infrastructure.yml
- removed the push on main dispatch trigger for this workflow
- added concurrency config so only one of `deployment to dev` or `ci infra` workflow is running at a time
- fixed potentially wrong secret setup
> fix: update ci infra workflow

- server/flyway/sql/V63__update_apt_app_role_display_name.sql
ref: #1798 (Adding User to APT Application Error):
Currently any Application Admin has problem adding users to APT role from FAM.
Issue is identified for missing display_name in fam_role table for APT application.
- Add flyway V63 to update APT fam_role for its missing display_name.
> fix: #1798 Add V63 flyway script for APT display name update.

- infrastructure/server/oidc_clients_apt.tf
- infrastructure/server/oidc_clients_fam.tf
- infrastructure/server/oidc_clients_fom.tf
- infrastructure/server/oidc_clients_results_exam.tf
- infrastructure/server/oidc_clients_silva.tf
- infrastructure/server/oidc_clients_spar.tf
- infrastructure/server/variables_provided.tf
closes: #1763 
Adjust Cognito App Clients read/write attributes to be consistent to avoid User Pools users necessary attributes missing when log on to different clients.
- updated `minimum_oidc_attribute_list` to include: `custom:idp_business_id`, `email`, `custom:idp_display_name`, `given_name`, `family_name`.
- adjusted all App Clients on Terraform file to reflect the change above.
Note: the `forest_client` App Client was having maximum attributes initially (unclear for the reason why it is very different than others) so no change for this app client.
> fix: #1763 Adjust Cognito app clients read/write attributes

- infrastructure/server/aurora-v2.tf
ref: #1740 
Post release to clean up and to back to normal configuration:
* decrease max_capacity = 1
* remove previous old version v13 _parameter_group
* allow_major_version_upgrade = false
> fix: #1740 AWS rds postgresql engine major version upgrade post release

- infrastructure/server/oidc_clients_fom.tf
ref: #1821 
- Missed the change for FOM test logout url change last time. Adjusted it in this pr.
- Also remove 'demo' logout.
> fix: #1821 FOM test environment logout url change.

- infrastructure/frontend/version.tf
- infrastructure/server/version.tf
I picked v5.99.1 for now as this is the version that we used for the [last successful deployment in PROD](https://github.com/bcgov/nr-forests-access-management/actions/runs/15477253127/job/43575553582).
Tested the deployment in Tools namespace, works fine https://github.com/bcgov/nr-forests-access-management/actions/runs/15766641334
> fix: #1846 added terraform required provider version

- .github/workflows/lza_reusable_terraform_frontend.yml
- .github/workflows/lza_tools_deployment.yml
- lza-infrastructure/landing-zone/frontend/terragrunt.hcl
- lza-infrastructure/landing-zone/frontend/tools/terragrunt.hcl
- lza-infrastructure/landing-zone/server/tools/terragrunt.hcl
- lza-infrastructure/terraform/frontend/cloudfront.tf
- lza-infrastructure/terraform/frontend/outputs.tf
- lza-infrastructure/terraform/frontend/variables_provided.tf
- lza-infrastructure/terraform/frontend/version.tf
- lza-infrastructure/terraform/frontend/waf-firewall-cloudfront.tf
- lza-infrastructure/terraform/server/outputs.tf
A Cloudfront portion for LZA to be merged to feature branch.
- added `lza_reusable_terraform_frontend.yml`
- added `aws-tools-deployment-frontend` step to `lza_tools_deployment.yml`
- added `lza-infrastructure/landing-zone/frontend/terragrunt.hcl` and `lza-infrastructure/landing-zone/frontend/tools/terragrunt.hcl` for frontend Terraform state management and Terraform variables.
- added `lza-infrastructure/terraform/frontend/cloudfront.tf` for distribution.
Note:  Due to currently we don't have vanity url yet for Cloudfront at LZA
* cloudfront_vanity_domain related variables are commented out.
* `front_end_redirect_path` is set to AWS default (hardcoded)
* `viewer_certificate` and `aliase` is also commented out.
- added lza-infrastructure/landing-zone/server/tools/terragrunt.hcl: configure …
> feat: #1920 lza migration for cloudfront

- lza-infrastructure/landing-zone/server/test/terragrunt.hcl
Minor addition for LZA TEST to work before domain switch:
- Default Cloudfront domain callback URL
> feat: #1950 Add default cloudfront callback url for LZA test.
